### ISSUE TITLE
Issue when creating site

### ISSUE THREAD

**Issue by jean-francois-labbe** [ParamagicDev/bridgetown-automation-tailwindcss#3]
I ran: `bridgetown new demo --apply="https://github.com/ParamagicDev/bridgetown-plugin-tailwindcss"`
ruby version: `ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]`
bridetown version: `bridgetown 0.16.0 "Crystal Springs"`
```ruby
         run    git clone --quiet https://github.com/ParamagicDev/bridgetown-automation-tailwindcss.git /tmp/bridgetown-automation-tailwindcss-20200907-44425-1etoxhj from "."
  Creating tailwind.config.js ...
Traceback (most recent call last):
	42: from ruby/2.7.1/bin/bridgetown:23:in `<main>'
	41: from ruby/2.7.1/bin/bridgetown:23:in `load'
	40: from ruby/2.7.1/gems/bridgetown-core-0.16.0/bin/bridgetown:22:in `<top (required)>'
	39: from ruby/2.7.1/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	38: from ruby/2.7.1/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	37: from ruby/2.7.1/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	36: from ruby/2.7.1/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	35: from ruby/2.7.1/gems/thor-1.0.1/lib/thor.rb:40:in `block in register'
	34: from ruby/2.7.1/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
	33: from ruby/2.7.1/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
	32: from ruby/2.7.1/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
	31: from ruby/2.7.1/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
	30: from ruby/2.7.1/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
	29: from ruby/2.7.1/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
	28: from ruby/2.7.1/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	27: from ruby/2.7.1/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	26: from ruby/2.7.1/gems/bridgetown-core-0.16.0/lib/bridgetown-core/commands/new.rb:60:in `new_site'
	25: from ruby/2.7.1/gems/bridgetown-core-0.16.0/lib/bridgetown-core/commands/new.rb:93:in `after_install'
	24: from ruby/2.7.1/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
	23: from ruby/2.7.1/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
	22: from ruby/2.7.1/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
	21: from ruby/2.7.1/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
	20: from ruby/2.7.1/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
	19: from ruby/2.7.1/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
	18: from ruby/2.7.1/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	17: from ruby/2.7.1/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	16: from ruby/2.7.1/gems/bridgetown-core-0.16.0/lib/bridgetown-core/commands/apply.rb:31:in `apply_automation'
	15: from ruby/2.7.1/gems/bridgetown-core-0.16.0/lib/bridgetown-core/commands/apply.rb:47:in `apply_after_new_command'
	14: from ruby/2.7.1/gems/bundler-2.1.4/lib/bundler.rb:376:in `with_clean_env'
	13: from ruby/2.7.1/gems/bundler-2.1.4/lib/bundler.rb:677:in `with_env'
	12: from ruby/2.7.1/gems/bundler-2.1.4/lib/bundler.rb:376:in `block in with_clean_env'
	11: from ruby/2.7.1/gems/bridgetown-core-0.16.0/lib/bridgetown-core/commands/apply.rb:49:in `block in apply_after_new_command'
	10: from ruby/2.7.1/gems/thor-1.0.1/lib/thor/actions.rb:187:in `inside'
	 9: from ruby-2.7.1/lib/ruby/2.7.0/fileutils.rb:139:in `cd'
	 8: from ruby-2.7.1/lib/ruby/2.7.0/fileutils.rb:139:in `chdir'
	 7: from ruby/2.7.1/gems/thor-1.0.1/lib/thor/actions.rb:187:in `block in inside'
	 6: from ruby/2.7.1/gems/bridgetown-core-0.16.0/lib/bridgetown-core/commands/apply.rb:50:in `block (2 levels) in apply_after_new_command'
	 5: from ruby/2.7.1/gems/bridgetown-core-0.16.0/lib/bridgetown-core/commands/concerns/actions.rb:80:in `apply_from_url'
	 4: from ruby/2.7.1/gems/thor-1.0.1/lib/thor/actions.rb:227:in `apply'
	 3: from ruby/2.7.1/gems/thor-1.0.1/lib/thor/actions.rb:227:in `instance_eval'
	 2: from https://raw.githubusercontent.com/ParamagicDev/bridgetown-plugin-tailwindcss/master/bridgetown.automation.rb:84:in `apply'
	 1: from https://raw.githubusercontent.com/ParamagicDev/bridgetown-plugin-tailwindcss/master/bridgetown.automation.rb:60:in `add_tailwind_config'
https://raw.githubusercontent.com/ParamagicDev/bridgetown-plugin-tailwindcss/master/bridgetown.automation.rb:60:in `read': No such file or directory @ rb_sysopen - demo/https:/raw.githubusercontent.com/ParamagicDev/bridgetown-plugin-tailwindcss/master/templates/tailwind.config.js (Errno::ENOENT)
```

**Comment by ParamagicDev** [comment]
@jean-francois-labbe Oops! Need to fix the readme. This project was renamed to `Bridgetown-automation-tailwindcss` instead of `Bridgetown-plugin-tailwindcss`.

Try this command:

`bridgetown new demo --apply="https://github.com/ParamagicDev/bridgetown-automation-tailwindcss"`

I will be fixing the readme as well.
